CREATE DATABASE qrstall;
USE qrstall;
CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  table_no INT NOT NULL,
  items TEXT NOT NULL,
  total DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);